from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Severity(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class BugType(Enum):
    LOGIC_ERROR = "logic_error"
    SECURITY_VULNERABILITY = "security_vulnerability"
    MEMORY_ISSUE = "memory_issue"
    SYNTAX_ERROR = "syntax_error"
    STYLE_VIOLATION = "style_violation"
    PERFORMANCE_ISSUE = "performance_issue"


@dataclass
class FeaturePoint:
    id: str
    name: str
    description: str
    files: list[str]
    start_line: Optional[int] = None
    end_line: Optional[int] = None


@dataclass
class Bug:
    id: str
    type: BugType
    severity: Severity
    title: str
    description: str
    file: str
    line: int
    end_line: Optional[int] = None
    suggestion: Optional[str] = None
    feature_point_id: Optional[str] = None
    # LLM scoring attributes (set by IssueScoringFilter)
    relevance_score: Optional[float] = None
    severity_score: Optional[float] = None
    score_reasoning: Optional[str] = None


@dataclass
class LineComment:
    path: str
    line: int
    body: str
    side: str = "RIGHT"


@dataclass
class StructureAnalysis:
    issues: list[Bug] = field(default_factory=list)
    summary: str = ""
    metrics: dict = field(default_factory=dict)


@dataclass
class MemoryAnalysis:
    issues: list[Bug] = field(default_factory=list)
    summary: str = ""
    patterns_found: list[str] = field(default_factory=list)


@dataclass
class LogicAnalysis:
    issues: list[Bug] = field(default_factory=list)
    summary: str = ""
    edge_cases: list[str] = field(default_factory=list)


@dataclass
class SecurityAnalysis:
    issues: list[Bug] = field(default_factory=list)
    summary: str = ""
    vulnerabilities: list[dict] = field(default_factory=list)


@dataclass
class PRSummary:
    title: str
    description: str
    files_changed: list[str]
    total_additions: int
    total_deletions: int
    feature_points: list[FeaturePoint]
    ai_summary: str = ""


@dataclass
class BugDetectionResult:
    has_bugs: bool
    total_count: int
    by_severity: dict[str, int]
    by_type: dict[str, int]
    bugs: list[Bug]


@dataclass
class AnalysisReport:
    pr_number: int
    repo_full_name: str
    pr_summary: PRSummary
    bug_detection: BugDetectionResult
    line_comments: list[LineComment]
    structure_analysis: StructureAnalysis
    memory_analysis: MemoryAnalysis
    logic_analysis: LogicAnalysis
    security_analysis: SecurityAnalysis
    generated_at: str = ""

    def to_markdown(self) -> str:
        sections = [
            "# PR Analysis Report",
            "",
            "## PR Summary",
            f"**Title**: {self.pr_summary.title}",
            f"**Files Changed**: {len(self.pr_summary.files_changed)}",
            f"**Additions**: +{self.pr_summary.total_additions}",
            f"**Deletions**: -{self.pr_summary.total_deletions}",
            "",
            self.pr_summary.ai_summary,
            "",
        ]

        if self.bug_detection.has_bugs:
            sections.extend([
                "## Bug Detection",
                f"**Total Issues Found**: {self.bug_detection.total_count}",
                "",
            ])
            for severity, count in self.bug_detection.by_severity.items():
                if count > 0:
                    sections.append(f"- {severity.upper()}: {count}")
            sections.append("")

            for bug in self.bug_detection.bugs:
                sections.extend([
                    f"### {bug.severity.value.upper()}: {bug.title}",
                    f"**File**: `{bug.file}:{bug.line}`",
                    f"**Type**: {bug.type.value}",
                    "",
                    bug.description,
                    "",
                ])
                if bug.suggestion:
                    sections.extend([
                        "**Suggestion**:",
                        bug.suggestion,
                        "",
                    ])
        else:
            sections.extend([
                "## Bug Detection",
                "No bugs detected in this PR.",
                "",
            ])

        sections.extend([
            "---",
            "*Generated by WiseCodeWatcher Multi-Agent Review System*",
        ])

        return "\n".join(sections)
