from output.models import AnalysisReport, LineComment


class ReportGenerator:
    def __init__(self, max_comment_length: int = 65535):
        self.max_comment_length = max_comment_length

    def generate_markdown(self, report: AnalysisReport) -> str:
        return report.to_markdown()

    def generate_github_review_body(self, report: AnalysisReport) -> str:
        sections = [
            "# PR Analysis Report",
            "",
            "## Summary",
            f"**PR**: #{report.pr_number}",
            f"**Repository**: {report.repo_full_name}",
            "",
        ]

        if report.pr_summary.ai_summary:
            sections.append(report.pr_summary.ai_summary)
            sections.append("")

        sections.extend([
            "## Analysis Results",
            "",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total Issues | {report.bug_detection.total_count} |",
        ])

        for severity, count in sorted(report.bug_detection.by_severity.items()):
            if count > 0:
                sections.append(f"| {severity.title()} | {count} |")

        sections.append("")

        if report.bug_detection.has_bugs:
            sections.append("## Issues Found")
            sections.append("")

            critical_high = [
                b for b in report.bug_detection.bugs
                if b.severity.value in ["critical", "high"]
            ]

            if critical_high:
                sections.append("### Critical/High Priority")
                for bug in critical_high[:10]:
                    sections.extend([
                        f"- **{bug.severity.value.upper()}** in `{bug.file}:{bug.line}`",
                        f"  - {bug.title}",
                        f"  - {bug.description[:200]}{'...' if len(bug.description) > 200 else ''}",
                        "",
                    ])

            medium_low = [
                b for b in report.bug_detection.bugs
                if b.severity.value in ["medium", "low"]
            ]

            if medium_low:
                sections.append(f"### Other Issues ({len(medium_low)} found)")
                sections.append("")
                for bug in medium_low[:5]:
                    sections.append(f"- `{bug.file}:{bug.line}`: {bug.title}")
                if len(medium_low) > 5:
                    sections.append(f"- ... and {len(medium_low) - 5} more")
                sections.append("")

        else:
            sections.extend([
                "## No Issues Found",
                "",
                "The automated analysis did not detect any significant issues in this PR.",
                "",
            ])

        sections.extend([
            "---",
            f"*Generated by WiseCodeWatcher at {report.generated_at}*",
        ])

        result = "\n".join(sections)
        if len(result) > self.max_comment_length:
            result = result[:self.max_comment_length - 100] + "\n\n... (truncated)"

        return result

    def generate_line_comments(self, report: AnalysisReport) -> list[dict]:
        comments = []
        seen_locations = set()

        for comment in report.line_comments:
            location = (comment.path, comment.line)
            if location in seen_locations:
                continue
            seen_locations.add(location)

            comments.append({
                "path": comment.path,
                "line": comment.line,
                "body": comment.body[:1000],
                "side": comment.side,
            })

        return comments[:50]

    def generate_json_report(self, report: AnalysisReport) -> dict:
        return {
            "pr_number": report.pr_number,
            "repo_full_name": report.repo_full_name,
            "generated_at": report.generated_at,
            "summary": {
                "title": report.pr_summary.title,
                "files_changed": len(report.pr_summary.files_changed),
                "additions": report.pr_summary.total_additions,
                "deletions": report.pr_summary.total_deletions,
                "feature_points": len(report.pr_summary.feature_points),
            },
            "bug_detection": {
                "has_bugs": report.bug_detection.has_bugs,
                "total_count": report.bug_detection.total_count,
                "by_severity": report.bug_detection.by_severity,
                "by_type": report.bug_detection.by_type,
            },
            "bugs": [
                {
                    "id": bug.id,
                    "type": bug.type.value,
                    "severity": bug.severity.value,
                    "title": bug.title,
                    "description": bug.description,
                    "file": bug.file,
                    "line": bug.line,
                    "suggestion": bug.suggestion,
                }
                for bug in report.bug_detection.bugs
            ],
            "line_comments_count": len(report.line_comments),
        }
